#!/bin/bash

#echo "Please enter your user name for ${REALM}, followed by [ENTER]:"
#read REMOTE_USERNAME
REMOTE_USERNAME="brauntin"

# Configuration
REMOTE_DOMAIN="AD"
REALM="${REMOTE_DOMAIN}.UNI-MARBURG.DE"
SHARES="HRZ_H\$/${REMOTE_USERNAME} HRZ_K\$"

#Color constants
RED="31"
GREEN="32"
BOLDGREEN="\e[1;${GREEN}m"
BOLDRED="\e[1;${RED}m"
ENDCOLOR="\e[0m"

echo 'Obtain/Renew Kerberos ticket'
kinit -R
if [ $? -ne 0 ] ; then
	kinit "${REMOTE_USERNAME}@${REALM}"
fi
klist

echo 'Root password required to mount filesystems with sudo'
sudo true
# Mount shares
for SHARE in $SHARES; do
  MOUNTPOINT="/var/run/user/${UID}/netmount/$(echo "$SHARE" | cut -f1 -d'$')"
  findmnt -n -M "${MOUNTPOINT}" > /dev/null
  if [ $? -eq 0 ] ; then
    echo -e "There is already a filesystem mounted under ${MOUNTPOINT}"
    continue
  fi
  echo -n -e "Mounting remote filesystem ${SHARE} "
  mkdir -p "${MOUNTPOINT}"
  sudo mount -t cifs //vsrz001.hrz-services.uni-marburg.de/${SHARE} "${MOUNTPOINT}" -o uid=${UID},gid=${UID},vers=2.0,user=${REMOTE_USERNAME},sec=krb5i,domain=${REMOTE_DOMAIN}
  if [ $? -eq 0 ]
  then
    echo -e "${BOLDGREEN}OK${ENDCOLOR}"
  else
    echo -e "${BOLDRED}FAILED${ENDCOLOR}"
  fi
done;

