# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" "md_mod" "raid0" "raid1" "raid10" "raid456" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "nfs" ];

  boot.swraid = {
    enable = true;
    mdadmConf = ''
      AUTO +linear
      MAILADDR root
      ARRAY /dev/md0 metadata=1.2 name=archlinux:0 UUID=77757fbb-37de-4f66-814b-056a28c7d2c0
    '';
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ee66b00f-a9c3-4b89-8afd-e1b459eed77a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C226-CC54";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/840d2046-c12a-48c7-ab2d-85b97ad026a5"; }
    ];

  fileSystems."/mnt/jbod" = {
    device = "/dev/md0";
    fsType = "ext4";
    options = [ "x-systemd.device-timeout=10" ];
  };

  fileSystems."/tank" = {
    device = "192.168.1.17:/tank";
    fsType = "nfs4";
    options = [
      "rw"
      "hard"
      "intr"
      "_netdev"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "timeo=900"
      "retrans=5"
      "sec=sys"
    ];
  };


  fileSystems."/backup" = {
    device = "192.168.1.17:/backup";
    fsType = "nfs4";
    options = [
      "rw"
      "hard"
      "intr"
      "_netdev"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "timeo=900"
      "retrans=5"
      "sec=sys"
    ];
  };


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
