# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "nfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ca51280-edb0-42af-949a-656ddc527c41";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6BEC-824D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/tank" = {
    device = "192.168.1.17:/tank";
    fsType = "nfs4";
    options = [
      "rw"
      "hard"
      "intr"
      "_netdev"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "timeo=900"
      "retrans=5"
      "sec=sys"
    ];
  };

    fileSystems."/downloads" = {
    device = "192.168.1.17:/tank/downloads";
    fsType = "nfs4";
    options = [
      "rw" "hard" "intr" "_netdev"
      "x-systemd.automount" "x-systemd.idle-timeout=600"
      "timeo=900" "retrans=5" "sec=sys"
    ];
  };

    fileSystems."/media" = {
    device = "192.168.1.17:/tank/media";
    fsType = "nfs4";
    options = [
      "rw" "hard" "intr" "_netdev"
      "x-systemd.automount" "x-systemd.idle-timeout=600"
      "timeo=900" "retrans=5" "sec=sys"
    ];
  };


  fileSystems."/backup" = {
    device = "192.168.1.17:/backup";
    fsType = "nfs4";
    options = [
      "rw"
      "hard"
      "intr"
      "_netdev"
      "x-systemd.automount"
      "x-systemd.idle-timeout=600"
      "timeo=900"
      "retrans=5"
      "sec=sys"
    ];
  };




#    fileSystems."/mnt/jbod" =
#    { device = "/dev/md127";
#      fsType = "ext4";
#    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7631c5f1-c14d-46ed-9914-b924c5395354"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp13s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
