# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  
#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/fcfa0d3f-786a-4d90-8900-86247cfcd19f";
#      fsType = "vfat";
#      options = [ "fmask=0077" "dmask=0077" ];
#    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fcfa0d3f-786a-4d90-8900-86247cfcd19f";
      fsType = "ext4";
    };

  #swapDevices =
  #  [ { device = "/dev/disk/by-uuid/958bb4ca-414d-4f01-b497-29e90d87c82a"; }
  #  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens18.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
